apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-replicas
  labels:
    task: task2
spec:
  strategy:
    rollingUpdate:
      maxSurge: 33%
      maxUnavailable: 33%
  replicas: 3
  selector: 
    matchLabels: 
      app: flask-app
  template: 
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - image: 52pbailey/task2-flask-app:v{{version}}
        name: flask-app
        env: 
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysqlpassword
              key: mysqlrootpassword
        env: 
        - name: YOUR_NAME
          value: {{YOUR_NAME}}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: flask-app
  name: flask-app
spec:
  ports: 
  - port: 5000
  selector:
    app: flask-app
  type: ClusterIP