apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-replicas
  labels:
    mysqldb: mysql
spec:
  strategy:
    rollingUpdate:
      maxSurge: 33%
      maxUnavailable: 33%
  replicas: 3
  selector: 
    matchLabels: 
      mysqldb: mysql
  template: 
    metadata:
      labels:
        mysqldb: mysql
    spec:
      containers:
      - image: 52pbailey/task2-db:v{{version}}
        name: mysql
        env: 
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysqlpassword
              key: mysqlrootpassword
---
apiVersion: v1
kind: Service
metadata:
  labels:
    mysqldb: mysql
  name: mysql
spec:
  type: ClusterIP
  selector:
    mysqldb: mysql
  ports:
    - port: 3306